; Super Mario Bros. 2 main payload
; Reconstructed from the pinned doppelganger ca65 listing

.scope smb2_main
    .include "../../platforms/late_fds/smb2/system/hardware.inc"
    .org $6000
    .include "../../platforms/late_fds/smb2/system/definitions.inc"
    .include "../../platforms/late_fds/smb2/system/interfaces.inc"
    .include "../../platforms/late_fds/smb2/system/reset.asm"
    .include "../../platforms/late_fds/smb2/rendering/vram_buffers.asm"
    .include "../../platforms/late_fds/smb2/game/scoring.asm"
    .include "../../platforms/late_fds/smb2/rendering/palettes.asm"
    .include "../../platforms/late_fds/smb2/rendering/name_tables.asm"
    .include "../../platforms/late_fds/smb2/game/mode_dispatch.asm"
    .include "../../platforms/late_fds/smb2/game/area_attributes.asm"
    .include "../../platforms/late_fds/smb2/game/area_objects.asm"
    .include "../../platforms/late_fds/smb2/game/scrolling.asm"
    .include "../../platforms/late_fds/smb2/game/player_control.asm"
    .include "../../platforms/late_fds/smb2/game/timers_and_flagpole.asm"
    .include "../../platforms/late_fds/smb2/game/projectiles.asm"
    .include "../../platforms/late_fds/smb2/game/blocks.asm"
    .include "../../platforms/late_fds/smb2/game/enemy_dispatch.asm"
    .include "../../platforms/late_fds/smb2/game/firebars_and_spawns.asm"
    .include "../../platforms/late_fds/smb2/game/piranha_and_platforms.asm"
    .include "../../platforms/late_fds/smb2/game/enemy_movement.asm"
    .include "../../platforms/late_fds/smb2/game/bowser.asm"
    .include "../../platforms/late_fds/smb2/rendering/enemy_graphics.asm"
    .include "../../platforms/late_fds/smb2/game/platforms.asm"
    .include "../../platforms/late_fds/smb2/game/player_enemy_collision.asm"
    .include "../../platforms/late_fds/smb2/game/platform_collision.asm"
    .include "../../platforms/late_fds/smb2/game/background_collision.asm"
    .include "../../platforms/late_fds/smb2/game/bounding_boxes.asm"
    .include "../../platforms/late_fds/smb2/rendering/sprite_helpers.asm"
    .include "../../platforms/late_fds/smb2/rendering/enemy_sprites.asm"
    .include "../../platforms/late_fds/smb2/rendering/block_sprites.asm"
    .include "../../platforms/late_fds/smb2/rendering/player_sprites.asm"
    .include "../../platforms/late_fds/smb2/rendering/relative_positions.asm"
    .include "../../platforms/late_fds/smb2/system/disk_loading.asm"
    .include "../../platforms/late_fds/smb2/game/continue_menu.asm"
    .include "../../platforms/late_fds/smb2/data/ui_messages.asm"
    .include "../../platforms/late_fds/smb2/data/course_bank.asm"
    .include "../../platforms/late_fds/smb2/audio/engine_core.asm"
    .include "../../platforms/late_fds/smb2/audio/music_engine.asm"
    .include "../../platforms/late_fds/smb2/audio/music_data.asm"
    .reloc
.endscope
