; Super Mario Bros. 2 MAIN payload
; Reconstructed from the pinned doppelganger ca65 listing

.scope smb2_main
    .include "system/hardware.inc"
    .org $6000
    .include "system/definitions.inc"
    .include "system/interfaces.inc"
    .include "system/reset.inc"
    .include "rendering/vram_buffers.inc"
    .include "game/scoring.inc"
    .include "rendering/palettes.inc"
    .include "rendering/name_tables.inc"
    .include "game/mode_dispatch.inc"
    .include "game/area_attributes.inc"
    .include "game/area_objects.inc"
    .include "game/scrolling.inc"
    .include "game/player_control.inc"
    .include "game/timers_and_flagpole.inc"
    .include "game/projectiles.inc"
    .include "game/blocks.inc"
    .include "game/enemy_dispatch.inc"
    .include "game/firebars_and_spawns.inc"
    .include "game/piranha_and_platforms.inc"
    .include "game/enemy_movement.inc"
    .include "game/bowser.inc"
    .include "rendering/enemy_graphics.inc"
    .include "game/platforms.inc"
    .include "game/player_enemy_collision.inc"
    .include "game/platform_collision.inc"
    .include "game/background_collision.inc"
    .include "game/bounding_boxes.inc"
    .include "rendering/sprite_helpers.inc"
    .include "rendering/enemy_sprites.inc"
    .include "rendering/block_sprites.inc"
    .include "rendering/player_sprites.inc"
    .include "rendering/relative_positions.inc"
    .include "system/disk_loading.inc"
    .include "game/continue_menu.inc"
    .include "data/ui_messages.inc"
    .include "data/course_bank.inc"
    .include "audio/engine_core.inc"
    .include "audio/music_engine.inc"
    .include "audio/music_data.inc"
    .reloc
.endscope
